// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBStuTUFrL4Bf6beADP6wiajRcMdt-b7BU',
    appId: '1:1022746005154:web:42372ea8c19df9550911fb',
    messagingSenderId: '1022746005154',
    projectId: 'pomodoro-85dd9',
    authDomain: 'pomodoro-85dd9.firebaseapp.com',
    storageBucket: 'pomodoro-85dd9.appspot.com',
    measurementId: 'G-FF3DE7XT2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9aTGavcnF30WqLaY_RNGx9U6io69ifWc',
    appId: '1:1022746005154:android:5f0f149a892dd7890911fb',
    messagingSenderId: '1022746005154',
    projectId: 'pomodoro-85dd9',
    storageBucket: 'pomodoro-85dd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNPDpfuwVtE7ueTcNmSHerPr9Gwb-VVe4',
    appId: '1:1022746005154:ios:0e50063eab6a30160911fb',
    messagingSenderId: '1022746005154',
    projectId: 'pomodoro-85dd9',
    storageBucket: 'pomodoro-85dd9.appspot.com',
    iosClientId: '1022746005154-q0588vs1q2pki5l262lunc5qi97tp85t.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomodoroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNPDpfuwVtE7ueTcNmSHerPr9Gwb-VVe4',
    appId: '1:1022746005154:ios:7be8ab98a85a59ac0911fb',
    messagingSenderId: '1022746005154',
    projectId: 'pomodoro-85dd9',
    storageBucket: 'pomodoro-85dd9.appspot.com',
    iosClientId: '1022746005154-au6f1l3o4bdr4n2gmi4lgkakop2rccu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomodoroApp.RunnerTests',
  );
}
